config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from config.views import index1

urlpatterns = [
    path('index1/', index1),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
# -*- coding: utf-8 -*-

from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('index2/', views.index2, name='index2'),
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

config/views.py
from django.shortcuts import render

def index1(request):
    return render(request, 'index1.html')

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from django.http import HttpResponseNotAllowed
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator 

def home(request):
    return render(request, 'pybo/home.html')

def index2(request):
    return render(request, 'pybo/index2.html')


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
      form = AnswerForm(request.POST)
      if form.is_valid():
          answer = form.save(commit=False)
          answer.create_date = timezone.now()
          answer.question = question
          answer.save()
          return redirect('pybo:detail', question_id=question.id)
      else:
          return HttpResponseNotAllowed('Only POST is possible.')
      context = {'question': question, 'form': form}
      return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/index1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'index1.css' %}">
        <title>Hello, pybo!</title>
  </style>
</head>
<body class="body">    
  <main key="1" class="card">
    <div class="card-content">
      <div class="card-header">
        <h1 class="text-2xl font-bold"><a href="index2.html">배틀그라운드란?</a></h1>
        <div class="items-center" variant="outline">
        </div>
      </div>
      <div class="p-6">
       <a href="index2.html">Details</a>
        <div class="h-72 w-full max-w-sm rounded-md border">
          <div class="p-4 text-sm">
            
            <p class="mt-4 leading-7">
                
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pybo/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'index1.css' %}">
        <title>Hello, pybo!</title>
    <a href="{% url 'pybo:index2' %}">Details</a>
  </style>
</head>
<body class="body">    
  <main key="1" class="card">
    <div class="card-content">
      <div class="card-header">
        <h1 class="text-2xl font-bold">배틀그라운드란?</h1>
        <div class="items-center" variant="outline">
            <a href="{% url 'pybo:index2' %}">Details</a>
        </div>
      </div>
      <div class="p-6">
       
        <div class="h-72 w-full max-w-sm rounded-md border">
          <div class="p-4 text-sm">
            
            <p class="mt-4 leading-7">
                
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

templates/pybo/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'index2.css' %}">
    <title>Hello, PUBG!</title>
</head>
<body>
<div class="slider">
    <input type="radio" name="slide" id="slide1" checked>
    <input type="radio" name="slide" id="slide2">
    <input type="radio" name="slide" id="slide3">
    <input type="radio" name="slide" id="slide4">
    <ul id="imgholder" class="imgs">
        <li><img src="{% static 'images/개요1.jpg' %}"></li>
        <li><img src="{% static 'images/개요2.png' %}"></li>
        <li><img src="{% static 'images/개요3.png' %}"></li>
        <li><img src="{% static 'images/개요4.png' %}"></li>
    </ul>
    <div class="bullets">
        <label for="slide1">&nbsp;</label>
        <label for="slide2">&nbsp;</label>
        <label for="slide3">&nbsp;</label>
        <label for="slide4">&nbsp;</label>
    </div>
</div>
</body>
<footer><p class="footer"><a href="{% url 'pybo:question_list' %}">뒤로가기</a></p></footer>
</html>

templates/pybo/index3.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mouse Coordinates</title>
  <link rel="stylesheet" href="index3.css">
</head>
<body>
  <div class="container">
    <h1>공백</h1>
    <div class="coordinates">
      <p id="xCoord">X: </p>
      <p id="yCoord">Y: </p>
    </div>
  </div>
  <script src="index3.js"></script>
</body>
</html>

templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
         <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

templates/pybo/question_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
{% load static %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
       <div class="container my-3">
    <div class="row">
        <!-- 기존 카드 -->
        <div class="col-md-3">
            <div class="card mb-3">
                <!-- 기존 카드 내용 -->
                <img src="{% static 'images/pubg1.png' %}" alt="no image">
                <div class="card-body">
                    <h5 class="card-title">프로젝트 개요</h5>
                    <h6 class="card-subtitle mb-2 text-muted">팀프로젝트 제3팀</h6>
                    <p>
                    지도:윤성혁선생님<br>
                    멤버:이시웅(팀장)<br>
                    멤버:박진우
                    <br>
                    <br>
                    <br>
                    <br>
                    <li>게임 설명</li>
                    <li>프로젝트 설명</li>
                    <li>변수 설명</li>
                    <li>분석 환경 및 변수 선택</li>
                    <br>
                    <a href="{% url 'pybo:home' %}" class="card-link">프로젝트 개요 보기</a>
                    </p>
                </div>
            </div>
        </div>
        <!-- 추가 카드 1 -->
        <div class="col-md-3">
            <div class="card mb-3">
                <!-- 추가 카드 1 내용 -->
                <img src="{% static 'images/pubg3.png' %}" alt="no image">
                <div class="card-body">
                    <h5 class="card-title">프로젝트 내용</h5>
                    <h6 class="card-subtitle mb-2 text-muted">프로젝트 내용 세분화</h6>
                    <p>
                    1.배틀그라운드 순위 예측 AI 모델링<br>
                    2.게임 데이터, 용어 분석<br>
                    3.데이터 전처리
                    입력 변수 선택 => 결측치/이상치 제거, 개인(Solo) 한정, 불필요칼럼 제거<br>
                    4.그리드 서치를 통한 모델 생성(릿지, 라쏘, 랜덤포레스트, 그라디언트)<br>
                    5.평가점수에 따른 최종 딥러닝모델 생성            
                    </p>
                    <a href="#" class="card-link">Card link</a>
                </div>
            </div>
        </div>
        <!-- 추가 카드 2 -->
        <div class="col-md-3">
            <div class="card mb-3">
               <div class="card-body">
                   <h5 class="card-title">프로젝트 개요</h5>
                   <h6 class="card-subtitle mb-2 text-muted">팀프로젝트 제3팀</h6>
                </div>
            </div>
        </div>
        <!-- 추가 카드 3 -->
        <div class="col-md-3">
            <div class="card mb-3">
                <!-- 추가 카드 3 내용 -->
            </div>
        </div>
    </div>
</div>

        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 처음페이지 -->
    {% if question_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page=1">처음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
    </li>
    {% endif %}
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
        <!-- 마지막페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.paginator.num_pages }}">마지막</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">마지막</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}